path:
  - /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/mtate/data/Gdata/nuebar_out/sqlite/merged/merged.db
  - /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/mtate/data/Gdata/tau_out/sqlite/merged/merged.db

graph_definition:
  arguments:
    columns: [0, 1, 2]
    detector:
      arguments: {}
      class_name: Prometheus
    dtype: torch.float32
    nb_nearest_neighbours: 8
    node_definition:
      arguments: {}
      class_name: NodesAsPulses
    input_feature_names: [sensor_pos_x, sensor_pos_y, sensor_pos_z, t]
  class_name: KNNGraph

pulsemaps:
  - photons

features:
  - sensor_pos_x
  - sensor_pos_y
  - sensor_pos_z
  - t

truth:
  - initial_state_energy
  - initial_state_type
  - initial_state_zenith
  - initial_state_azimuth
  - initial_state_x
  - initial_state_y
  - initial_state_z
  - interaction

index_column: event_no
truth_table: mc_truth
seed: 42

selection:
  train: "event_no % 5 < 4 & (initial_state_type == -12 | initial_state_type == 16)"
  test: "event_no % 5 == 4 & (initial_state_type == -12 | initial_state_type == 16)"
